### ISSUE TITLE
Script should kill more plex processes 

### ISSUE THREAD

**Issue by ocalvo** [Mart11/PlexUpdate4Win#1]
In particular the transcoder process the tuner process and the Plex script processes

**Comment by ocalvo** [comment]
I normally do ps *plex* | kill - force in powershell

**Comment by ocalvo** [comment]
(*) plex(*)

**Comment by ocalvo** [comment]
asterisk plex asterisk

**Comment by Mart11** [comment]
A taskkill command with a /T switch should do that (if all Plex processes are as child processes of PMS). But to be sure, added a new line with a taskkill command in the loop for killing all ...plex...exe processes. Fixed/added in v1.1
